name: Create Release With Artifacts
on:
  push:
    paths:
      - "module.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install rustup
        run: curl -y --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

      - name: Use nightly toolchain
        run: rustup default nightly

      - name: Install wasm-pack
        run: cargo install wasm-pack
        
      - name: Run wasm-pack
        run: wasm-pack build --target web
      
      - name: Create module zip
        run: zip rust-module module.json LICENSE index.js pkg/rust_module.js pkg/rust_module_bg.wasm pkg/snippets/*
        
      - name: Get version number
        id: get-version
        run: echo "version=v$(jq -r .version module.json)" >> $GITHUB_OUTPUT
        
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get-version.outputs.version }}
          name: ${{ steps.get-version.outputs.version }}
          body: TODO
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json,./rust-module.zip"
          
