name: Build Release Artifacts
on: 
  push:
    paths:
      - "module.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Adds the files in this repository to the evironment this action runs in
      - name: Prepare Environment
        uses: actions/checkout@v3
        
      # Installs the tool which compiles rust into webassembly
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        
      # Compile rust into webassembly
      - name: Build wasm Files
        run: wasm-pack build --target web
      
      # Compresses the files the module needs into a zip file
      - name: Zip Files
        run: zip rust-module module.json LICENSE index.js pkg/rust_module.js pkg/rust_module_bg.wasm
        
      # Get the release number from module.json
      - name: Version Number
        id: get-version
        run: echo "version::$(echo -n "v" ; jq -r .version module.json echo)" >> $GITHUB_OUTPUT
        
      # Creates the github release for this version
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get-version.outputs.version }}
          name: ${{ steps.get-version.outputs.version }}
          body: TODO
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json,./rust-module.zip"
          
      # Updates the latest release to point to this one
      - name: Update Latest
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: Latest
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json,./rust-module.zip"
          
