name: Create Release With Artifacts
on:
  push:
    paths:
      - "module.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        
      - name: Run wasm-pack
        run: wasm-pack build --target web
      
      - name: Create module zip
        run: zip rust-module module.json LICENSE index.js pkg/rust_module.js pkg/rust_module_bg.wasm
        
      - name: Get version number
        id: get-version
        run: echo "version=v$(jq -r .version module.json)" >> $GITHUB_OUTPUT
        
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get-version.outputs.version }}
          name: ${{ steps.get-version.outputs.version }}
          body: TODO
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json,./rust-module.zip"
          
